name: murderers
description: A murder game.

version: 0.0.1+3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^1.0.6
  firebase_auth: ^0.6.6
  firebase_messaging: ^2.0.3
  flare_flutter: any
  flutter_svg: ^0.10.3
  flutter_villains: ^1.2.0
  google_sign_in: ^3.2.2
  http: ^0.12.0
  intl: ^0.15.7
  json_annotation: ^2.0.0
  rxdart: ^0.21.0
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/google_icon.svg
    - images/deaths.flr

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: Signature
      fonts:
        - asset: fonts/Raleway-ExtraBold.ttf
    - family: Mono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
